#!/bin/bash


# Check if terminal supports colors output
colors_no="$(LC_ALL=C tput colors 2>/dev/null)"

BOOTUP=""
if [ -n "$colors_no" ]; then
  if [ "$colors_no" -ge 8 ]; then
    [ -z "$SETCOLOR_SUCCESS" ] && SETCOLOR_SUCCESS="echo -en \\033[1;32m"
    [ -z "$SETCOLOR_FAILURE" ] && SETCOLOR_FAILURE="echo -en \\033[1;31m"
    [ -z "$SETCOLOR_WARNING" ] && SETCOLOR_WARNING="echo -en \\033[1;33m"
    [ -z "$SETCOLOR_NORMAL"  ] && SETCOLOR_NORMAL="echo -en \\033[0;39m"
    BOOTUP="color"
  fi
fi

#--- Sub function
initenv() {

  [ -e "${_SCICMDRC}" ] && mv ${_SCICMDRC} ${_SCICMDRC}.bak

  $SETCOLOR_WARNING;
  echo "Start to initenv:"
  echo "Touch ${_SCICMDRC} and write md5sum: $_SCICMD_MD5SUM"
  echo "md5sum = $_SCICMD_MD5SUM" >> ${_SCICMDRC}

  echo "Check ~/bin and \$PATH ..."
  read -p '[Enter] to og or [Ctrl + c] to exit'
  #[ -d "$_BIN_PATH" ] || mkdir ~/bin
  if [ -z "$(echo ":${PATH}:" | grep -E "\:${HOME}\/bin\:") " ] ; then
    export PATH=${PATH}:${HOME}/bin
    [ "${SHELL}" == '/bin/bash' ] && echo "export PATH=${PATH}:${HOME}/bin" >> ~/.bashrc
  fi

  echo "Install required package ..."
  read -p '[Enter] to go or [Ctrl + c] to exit'
  sudo apt install $_REQUIRED_PACKAGE
  [ "$?" != '0' ] && $SETCOLOR_FAILURE && echo "Install required packages error ! Please install required packages : $_REQUIRED_PACKAGE then run $0 again " && exit 1;

  $SETCOLOR_SUCCESS ; echo "Environment check well for go. "; $SETCOLOR_NORMAL
}

update() {
  echo "Start to update"
  

}

print_help() {
  echo " s3fs-public	: Setup public read s3fs with automount"
  echo " s3fs-purge	: Setup public read s3fs with automount"
  echo " initenv	: Install and intifor environment for scicmd tool"
  echo " update		: Update Scicmd packeage"
  echo " help		: Print this help menu"
}


#--- End of sub

### Main

_SCICMDRC="${HOME}/.scicmdrc"
_BIN_PATH="${HOME}/bin"
_REQUIRED_PACKAGE="s3fs jq python-pip curl wget git"

_REALPATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
#echo $_REALPATH
#read
[ -d "$_BIN_PATH" ] || mkdir ~/bin
#[ "${_REALPATH}" != "${_BIN_PATH}/scicmd"  ]  && cp $_REALPATH "${_BIN_PATH}/scicmd" && chmod +x "${_BIN_PATH}/scicmd" &&  sync  && exec ${_BIN_PATH}/scicmd ;
if [ "${_REALPATH}" != "${_BIN_PATH}/scicmd"  ] ; then
	wget https://raw.githubusercontent.com/ceasar-sun/scicmd/master/scicmd -O "${_BIN_PATH}/scicmd"
	sync; sync;
	chmod +x "${_BIN_PATH}/scicmd"
	exec ${_BIN_PATH}/scicmd ;
fi

_SCICMD_MD5SUM="$( md5sum $_REALPATH | awk '{print $1}')"

[ -f "${_SCICMDRC}" ] || initenv;

read -p '[stop here ]'

case "$1" in
  initenv)
        initenv
        ;;
  s3fs-public)
        s3fs-public
        ;;
  s3fs-purge)
        s3fs-purge
        ;;

  update)
        update
        ;;
  *)
        print_help;
        exit 1
esac



exit 0
